# Generated by Django 5.2.5 on 2025-08-21 11:46

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название задачи"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Описание задачи",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "создано"),
                            ("underway", "в работе"),
                            ("completed", "завершено"),
                        ],
                        default="created",
                        verbose_name="Статус задачи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
    ]
